### ISSUE TITLE
Request additional support for models not supported by vLLM

### ISSUE THREAD

**Issue by ai-yeongji** [StableFluffy/LogicKor#12]
Currently, the generator.py code uses the LLM class of vLLM when loading the model, and I would like you to provide it as an option so that we can test for models that are not supported by vLLM.

**Comment by realsigridjin** [comment]
@ai-yeongji 

Thank you for your interest in our project and for suggesting the addition of support for models not currently supported by vLLM. We greatly appreciate your enthusiasm and willingness to contribute to the development of our project.

Unfortunately, due to time constraints and other priorities, we are currently unable to allocate resources to directly implement the feature you have requested. However, we would be more than happy to consider a pull request from you if you are able to implement the necessary changes using the transformers library.

If you have any further questions or concerns, please don't hesitate to reach out to us :)
